### ISSUE TITLE
Are there any plans to port for PySide2?

### ISSUE THREAD

**Issue by AndiLi99** [hmeine/qimage2ndarray#12]
Or is PySide2 already supported?

**Comment by AndiLi99** [comment]
The changelog indicates support for PySide and not PySide2 was added. Installing with PySide2 with conda doesn't seem to work.

**Comment by johndoe46** [comment]
Pypi package is not updated as well. Until then, just clone the repo and install with ```python setup.py install```

**Comment by johndoe46** [comment]
```
import cv2
from qimage2ndarray import array2qimage
img = cv2.imread("/path/to/pic.tif")
cute_img = array2qimage(img)
print(type(cute_img))
```
Output:

```
<class 'PySide2.QtGui.QImage'>
Process finished with exit code 0
```

**Comment by hmeine** [comment]
1.7 is released with PySide2 support. Please re-open or open new issues if you see remaining issues.
