### ISSUE TITLE
License compatibility to GPL

### ISSUE THREAD

**Issue by manns** [hmeine/qimage2ndarray#14]
I would like to use qimage2ndarray inside my project pyspread (https://manns.github.io/pyspread/), which is GPL licensed.

The Websitye mentions that qimage2ndarray is BSD licensed. However, your license file contains a paragraph about the University of Hamburg, of which I fear that is GPL incompatible.

Could you please adjust / extend the license so that the code can be used under the GPL v3 license?

**Comment by hmeine** [comment]
I believe this to be a standard [3-clause BSD license](https://opensource.org/licenses/BSD-3-Clause) that should be compatible with the GPL.

Would you feel more confident if I replaced the name of my former employer with the generic placeholder as mentioned on https://opensource.org/licenses/BSD-3-Clause ?

**Comment by manns** [comment]
Yes that would be great.
