### ISSUE TITLE
numpy boolean subtract deprecated in normalise = True

### ISSUE THREAD

**Issue by c-arthurs** [hmeine/qimage2ndarray#17]
Hi, 

I'm using your qimage2ndarray.array2qimage to display masked images with normalise = True. 
It seems to be tripping up on binary np arrays with the below error message - 

  File "/Users/miniconda3/envs/core/lib/python3.6/site-packages/qimage2ndarray/__init__.py", line 318, in array2qimage
    array = _normalize255(array, normalize)
  File "/Users/miniconda3/envs/core/lib/python3.6/site-packages/qimage2ndarray/__init__.py", line 192, in _normalize255
    scale = 255. / (nmax - nmin)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

Weirdly though it didn't trip up when I made a tiny test image so let me know if you can replicate it - otherwise ill need to spend more time looking at my images. 
Thanks for the help,
Callum

**Comment by hmeine** [comment]
The `scale` computation is for normalizing image values. If you have boolean arrays, there is not much to normalize, but I assume you want to scale them to 0…255, right? That sounds like a sensible request, and we could special-case that. I don't have time to try that out right now, but it sounds like a simple thing to fix.

Could you help with that, e.g., by providing a test image, a test function, or a full PR?

**Comment by c-arthurs** [comment]
Thanks, it was actually easy to fix by converting bool to float. Mock data is below. I also created the pull request. 

array = np.ones((10,10))
array[5, 5] = 0
array = array.astype(bool)

**Comment by hmeine** [comment]
Cool. I applied a similar fix at the same spot. Thanks for bringing this up and debugging!
