### ISSUE TITLE
Support for Pyside6 anytime soon?

### ISSUE THREAD

**Issue by christli7** [hmeine/qimage2ndarray#22]
Hi, I just wanna ask if you are planning to support Pyside6 soon?
Thank you!

**Comment by hmeine** [comment]
I am in favor of doing so, but I do not use PySide myself and am not aware of what has to be done at all.

Do you have an idea what would be necessary, and/or would be able to look into that?  I assume the amount of work might be minimal, possibly just extending the version check / backend decision appropriately.

**Comment by Oli4** [comment]
Hey I also ran into the PySide6 issue and could fix it with the same changes @hmeine  made in his last commits. Are there any problems with these changes or why is there no new release yet? I really appreciate the great work on this package!

**Comment by HDembinski** [comment]
Agreed, it would be great to have a release with PySide6 support :)

**Comment by hmeine** [comment]
If anyone of you working with PySide6 knows how to tackle the CircleCI problem with PySide6 (something like libEGL not found), I'd be glad. One might need to know more about CircleCI than I do.

**Comment by hmeine** [comment]
I just released version 1.9.0.

**Comment by hmeine** [comment]
Cool, that helped – I had to add `apt-get update` and installation of `xkbcommon0` as well, but now I am a good step forward. However, now I see something that looks like real unit test errors: https://app.circleci.com/pipelines/github/hmeine/qimage2ndarray/39/workflows/40cdbabe-ec45-4eeb-87f4-f89fba71efbd/jobs/83

The tests complain about missing QImage attributes "byteCount" and "numBytes" (one of them would be needed).

**Comment by hmeine** [comment]
Wow! The seem to have renamed the method again, now into "sizeInBytes"… https://doc.qt.io/qtforpython/PySide6/QtGui/QImage.html#PySide6.QtGui.PySide6.QtGui.QImage.sizeInBytes

**Comment by hmeine** [comment]
Ah, sizeInBytes was necessary in order to support images > 2GiB and has been introduced in Qt 5.10.

**Comment by hmeine** [comment]
Nice, now even CircleCI is happy again (for the first time in a long time)!
