### ISSUE TITLE
QImage format can not be determined

### ISSUE THREAD

**Issue by Oli4** [hmeine/qimage2ndarray#29]
I get the following error when using qimage2ndarray with pyside6.3 or pyside6.4 (I haven't tested other versions)

 
```bash
File "/home/morelle/.cache/pypoetry/virtualenvs/eyelab--UaGblaG-py3.10/lib/python3.10/site-packages/qimage2ndarray/qimageview_python.py", line 136, in qimageview
    if qimage_format.bits not in (8, 16, 32, 64):
AttributeError: 'NoneType' object has no attribute 'bits'
```

I think the problematic line is here: 
https://github.com/hmeine/qimage2ndarray/blob/03d823277e6e1daff5a720c19f6a31b12a7a75a3/qimage2ndarray/qimageview_python.py#L105

The format names do not seem to be available in the QImage dir anymore and `QImage.format()`also return a format string in the form `Format.Format_RGB32` for example. It works if you replace in the line above `QtGui.QImage` it with `QtGui.QImage.Format`

Currently I place this code directly after the first qimage2ndarray import to patch the issue until a new release

```python
import qimage2ndarray
# Monkeypatch qimage2ndarray until new version (> 1.9.0)
for name, qimage_format in qimage2ndarray.qimageview_python.FORMATS.items():
    if name in dir(QtGui.QImage.Format):
        qimage_format.code = getattr(QtGui.QImage, name)
```

Thanks a lot for qimage2ndarray. I use it a lot.

**Comment by hmeine** [comment]
With PySide6, while QImage no longer has `Format_RGB32` and friends in its `dir()`, directly accessing it still works, and `QImage.Format_Indexed8 is QImage.Format.Format_Indexed8` is `True`.

In PyQt5, those constants are just `int`s and `QImage.Format_Indexed8 == QImage.Format.Format_Indexed8` holds, but not `QImage.Format_Indexed8 is QImage.Format.Format_Indexed8`.
