### ISSUE TITLE
support for pyqt5

### ISSUE THREAD

**Issue by rhoef** [hmeine/qimage2ndarray#4]
As far as I can tell there is no support for pyqt5 yet. Is it planned to port the module?

**Comment by hmeine** [comment]
Sure. I have not started using [py]Qt5 myself, yet, so I did not look at a port either.  However, I am highly interested in making qimage2ndarray as compatible as possible, as you could probably see. ;-)

**Comment by rhoef** [comment]
I just make a forke and started a pyqt5 branch. Pull request is comming soon...

**Comment by hmeine** [comment]
Thanks for the PR.  I have finally updated my Linux machine, tested and integrated (parts of) your PR, made some more changes and a release.
I acknowledged you in the README. Should I spell you "Hoefler" or is it "Höfler"? Thanks again.
