### ISSUE TITLE
Release current version

### ISSUE THREAD

**Issue by montefra** [hmeine/qimage2ndarray#8]
Some colleagues of mine and I are developing a PyQt application and we use your package as dependence.

Unfortunately the current released version fails if numpy is not already installed.
```
Collecting qimage2ndarray==1.5.0
  Downloading qimage2ndarray-1.5.tar.gz (188kB)
    100% |████████████████████████████████| 188kB 60.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-btisfos7/qimage2ndarray/setup.py", line 6, in <module>
        import sys, os, glob, numpy
    ImportError: No module named 'numpy'
```

I've tested the current version in master and I can install it without any issue.

Would you mind release the current master? (I guess that v1.5.1 would be the correct number)

Thank you in advance

**Comment by hmeine** [comment]
Oh, thanks for bringing this to my attention.  Apparently, the cleanups in b4ef315a00990ae59caac0d90977404813866944 justify a release 1.5.1.

**Comment by montefra** [comment]
@hmeine I would say so. 
At least it makes installing on clean systems work

**Comment by hmeine** [comment]
OK, 1.5.1 is released: https://pypi.python.org/pypi/qimage2ndarray/1.5.1

I would be happy about feedback.

**Comment by montefra** [comment]
@hmeine : thank you very much. I'll let you know in the next days.

**Comment by montefra** [comment]
it works like charm:
```
-> pip install --no-cache-dir qimage2ndarray                                                                                                               
Collecting qimage2ndarray
  Downloading qimage2ndarray-1.5.1.tar.gz (188kB)
    100% |████████████████████████████████| 192kB 55.5MB/s 
Collecting numpy (from qimage2ndarray)
  Downloading numpy-1.10.4.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 64.4MB/s 
Installing collected packages: numpy, qimage2ndarray
  Running setup.py install for numpy ... done
  Running setup.py install for qimage2ndarray ... done
Successfully installed numpy-1.10.4 qimage2ndarray-1.5.1
```

Thank you again

**Comment by hmeine** [comment]
Cool, thanks for testing / feedback.
